<?php
/**
 * Item display page view
 * 
 * @version $Id: list.phtml,v 1.4 2007-12-04 16:54:49 seva Exp $
 */

#require_once 'Zend/Controller/Front.php';

// Render common HTML header
#echo $this->render('partials/html_header.phtml');
$title = 'Item List:';
$this->headTitle($title);
?>
<h2><?=$this->escapeHtml($title)?></h2>
<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escapeHtml($this->error); ?>
	</div>
<?php elseif ($this->paginator && count($this->paginator)): ?>
	<div class="item_container" width="100%">
		<table class="item_list">
			<tr>
				<th width="50px"></th>
				<th width="200px">Item</th>
				<th>Category</th>
				<th>Description</th>
				<th>Cost</th>
				<th>Vespene</th>
				<th>Max</th>
				<th>Level</th>
				<th>Short Name</th>
			</tr>
			<?php foreach ($this->paginator as $item): ?>
				<tr class='item'>
					<?php if (empty($item->getImage())): ?>
						<td width="50px"><li></td>
					<?php else: ?>
						<td width="50px"><a href="<?= $this->url('item', ['action' => 'show', 'id' => $item->getId()]) ?>"><img src="/sc/img/<?= $item->getImage() ?>" width="38px" /></td>
					<?php endif; ?>
					<td width="200px"><a href="<?= $this->url('item', ['action' => 'show', 'id' => $item->getId()]) ?>"><?=$this->escapeHtml($item->getLongName()) ?></td>
					<td><?= $this->escapeHtml($item->getCategory()) ?></td>
					<td><?= $this->escapeHtml($item->getDescription()) ?></td>

					<?php if ($item->getCrystals() > 0): ?>
						<td><?= $this->escapeHtml($item->getCrystals()) ?></td>
					<?php else: ?>
						<td></td>
					<?php endif; ?>

					<?php if ($item->getVespene() > 0): ?>
						<td><?= $this->escapeHtml($item->getVespene()) ?></td>
					<?php else: ?>
						<td></td>
					<?php endif; ?>

					<?php if ($item->getMax() > 1): ?>
						<td><?= $this->escapeHtml($item->getMax()) ?></td>
					<?php else: ?>
						<td></td>
					<?php endif; ?>

					<?php if ($item->getRequiredLevel() > 0): ?>
						<td><?= $this->escapeHtml($item->getRequiredLevel()) ?></td>
					<?php else: ?>
						<td></td>
					<?php endif; ?>

					<td><?= $this->escapeHtml($item->getItemName()) ?></td>
				</tr>
			<?php endforeach; ?>
		</table>
	</div>
	<?= $this->paginationControl(
		// The paginator object:
		$this->paginator,
		// The scrolling style:
		'sliding',
		// The partial to use to render the control:
		'partial/paginator',
		// The route to link to when a user clicks a control link:
		['route' => 'item']
	)
	?>
<?php else: ?>
	No items have been selected.
<?php endif; ?>

<!--?= $this->render('partials/html_footer.phtml'); ?-->
