<?php
/**
 * Item display page view
 * 
 * @version $Id: show.phtml,v 1.4 2007-12-04 16:54:49 seva Exp $
 */

#require_once 'Zend/Controller/Front.php';

// Render common HTML header
#echo $this->render('partials/html_header.phtml');

$title = 'Item:';
$this->headTitle($title);
?>

<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escape($this->error); ?>
	</div>
<?php elseif (! empty($this->item)): ?>

<div class="item_container">
	<table class="item_detail">
		<tr>
			<?php if (empty($item->getImage())): ?>
				<td width="250"></td>
			<?php else: ?>
				<td width="250"><img src="/sc/img/<?= $item->getImage() ?>" width="250" /></td>
			<?php endif; ?>
			<td width="100%" style="vertical-align:top">
				<table class="item_title" width="100%">
					<tr>
						<th width='100%' style="text-align: center;"><?= $this->escapeHtml($item->getLongName()) ?></th>
					</tr>
				</table>
				<table class="item_data">
					<tr>
						<th width="150px" align="right">Category :</th>
						<td>
							<a href="<?= $this->url('item', ['action' => 'match', 'category' => $this->escapeUrl($item->getCategory())])?>">
								<?= $this->escapeHtml($item->getCategory()) ?>
							</a>
						</td>
					</tr>
					<tr>
						<th width="150px" align="right">Cost :</th>
						<td><?= $this->escapeHtml($item->getCrystals()) ?></td>
					</tr>
					<?php if ($item->getVespene() > 0): ?>
						<tr>
							<th width="150px" align="right">Vespene :</th>
							<td><?= $this->escapeHtml($item->getVespene()) ?></td>
						</tr>
					<?php endif; ?>
					<?php if ($item->getMax() > 1): ?>
						<tr>
							<th width="150px" align="right">Max Carried :</th>
							<td><?= $this->escapeHtml($item->getMax()) ?></td>
						</tr>
					<?php endif; ?>
					<?php if ($item->getRequiredLevel() > 0): ?>
						<tr>
							<th width="150px" align="right">Required Level :</th>
							<td><?= $this->escapeHtml($item->getRequiredLevel()) ?></td>
						</tr>
					<?php endif; ?>
					<tr>
						<th width="150px" align="right">Short Name :</th>
						<td><?= $this->escapeHtml($item->getItemName()) ?></td>
					</tr>
				</table>
				<table width="100%">
					<tr>
						<td><?= $this->escapeHtml($item->getDescription()) ?></td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
	<br/>

</div>
<?php else: ?>
	No item has been selected.
<?php endif; ?>

<!--?= $this->render('partials/html_footer.phtml'); ?-->
