<?php
/**
 * Race display page view
 * 
 * @version $Id: show.phtml,v 1.4 2007-12-04 16:54:49 seva Exp $
 */

#require_once 'Zend/Controller/Front.php';

// Render common HTML header
#echo $this->render('partials/html_header.phtml');

$title = 'Race:';
$this->headTitle($title);
?>

<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escapeHtml($this->error); ?>
	</div>
<?php elseif (! empty($this->race)): ?>
	<div class="race_container">
		<table class="race_detail">
			<tr>
				<td width="100%"><table width="100%">
					<tr>
						<table width="100%">
							<tr>
								<td><img src="/sc/img/<?= $race->getImage() ?>" width="250" /></td>
								<td width="100%" style="vertical-align:top">
									<table class="race_title" width="100%">
										<tr>
											<th width='100%' style="text-align: center;"><?= $this->escapeHtml($race->getLongName()) ?></th>
										</tr>
									</table>
									<table class="race_data">
										<tr>
											<th width="150px" align="right">Faction :</th>
											<td><a href="<?= $this->url('faction', ['action' => 'show', 'id' => $race->getFaction()]) ?>"><?= $this->escapeHtml($race->getFactionName()) ?></a></td>
										</tr>
										<tr>
											<th width="150px" align="right">Type :</th>
											<td><?= $this->escapeHtml($race->getType()) ?></td>
										</tr>
										<?php if (!empty($race->getParentName())): ?>
											<tr>
												<th width="150px" align="right">Summoned From :</th>
												<td><a href="<?= $this->url('race', ['action' => 'show', 'name' => $race->getParentName()]) ?>"><?= $this->escapeHtml($race->getParentLongName()) ?></a></td>
											</tr>
										<?php endif; ?>
										<?php if ($race->getRequiredLevel() > 0): ?>
											<tr>
												<th width="150px" align="right">Required Level :</th>
												<td><?= $this->escapeHtml($this->race->getRequiredLevel()) ?></td>
											</tr>
										<?php endif; ?>
										<?php if ($race->getTechLevel() > 0): ?>
											<tr>
												<th width="150px" align="right">Required Tech Level :</th>
												<td><?= $this->escapeHtml($trace->getTechLevel()) ?></td>
											</tr>
										<?php endif; ?>
									</table>
									<table width="100%">
										<tr>
											<td><?= $this->escapeHtml($race->getDescription()) ?></td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</tr>
				</td></table>
			</tr>
		</table>
		<br/>
		<?php if (! empty($this->upgrades)): ?>
			<ul><table class="upgrade_detail" width='100%'>
				<tr>
					<th></th>
					<th></th>
					<th></th>
					<th colspan="3"><center>-Upgrade Requirement-</center></th>
					<th colspan="3"><center>----- Cost to Invoke -----</center></th>
					<th>Energy/</th>
					<th></th>
				</tr>
				<tr>
					<th></th>
					<th>Upgrade</th>
					<th><center>Levels</center></th>
					<th><center>Min Lvl</center></th>
					<th><center>Crystals</center></th>
					<th><center>Vespene</center></th>
					<th><center>Energy</center></th>
					<th><center>Crystals</center></th>
					<th><center>Vespene</center></th>
					<th><center>Second</center></th>
					<th>Description</th>
				</tr>
				<?php foreach ($this->upgrades as $upgrade): ?>
					<tr class='race_upgrades' width='100%'>
						<?php if (empty($upgrade->getImage())): ?>
							<td><li></td>
						<?php else: ?>
							<td><img src="/sc/img/<?= $upgrade->getImage() ?>" width="38px" /></td>
						<?php endif; ?>
						<td><b><?= $this->escapeHtml($upgrade->getLongName()) ?><?= (($upgrade->getCategory() > 0) ? "<br><font color='cyan'> +ultimate" . $this->escapeHtml($upgrade->getCategory()) . "</font>" : "") ?></b></td>
						<td><center><?= $upgrade->getMaxLevel() ?></center></td>
						<td><center><?= ($upgrade->getRequiredLevel() > 1) ? $upgrade->getRequiredLevel() : "" ?></center></td>
						<td><center><?= ($upgrade->getCostCrystals() > 0) ? $upgrade->getCostCrystals() : "" ?></center></td>
						<td><center><?= ($upgrade->getCostVespene() > 0) ? $upgrade->getCostVespene() : "" ?></center></td>
						<td><center><?= ($upgrade->getEnergy() > 0) ? $upgrade->getEnergy() : "" ?></center></td>
						<td><center><?= ($upgrade->getCrystals() > 0) ? $upgrade->getCrystals(): "" ?></center></td>
						<td><center><?= ($upgrade->getVespene() > 0) ? $upgrade->getVespene() : "" ?></center></td>
						<td><center><?= ($upgrade->getRecurringEnergy() > 0) ? : "" ?></center></td>
						<td><?= $upgrade->getDescription().'&nbsp'.$upgrade->getInvoke().'&nbsp'.$upgrade->getBind() ?></td>
					</tr>
				<?php endforeach; ?>
				<tr>
					<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
					<td><img src="/images/spacer.gif" width="100px" height="1"/></td>
					<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
					<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
					<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
					<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
					<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
					<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
					<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
					<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
					<td width="100%"></td>
				</tr>
			</table></ul>
		<?php endif; ?>
	</div>
<?php else: ?>
	No race has been selected.
<?php endif; ?>
</div>

<!--?= $this->render('partials/html_footer.phtml'); ?-->
