<?php
/**
 * Player display page view
 * 
 * @version $Id: list.phtml,v 1.4 2007-12-04 16:54:49 seva Exp $
 */

#require_once 'Zend/Controller/Front.php';

// Render common HTML header
#echo $this->render('partials/html_header.phtml');

$title = 'Player List:';
$this->headTitle($title);
?>

<h2><?= $this->escapeHtml($title) ?></h2>

<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escape($this->error); ?>
	</div>
<?php elseif (count($this->paginator)): ?>

	<?= $this->paginationControl(
		// The paginator object:
		$this->paginator,
		// The scrolling style:
		'sliding',
		// The partial to use to render the control:
		'partial/paginator',
		// The route to link to when a user clicks a control link:
		['route' => 'race']
	)?>

	<table class="player_list">
		<tr>
			<th width="50px">ID</th>
			<th width="200px">Name</th>
			<th width="200px">Steam ID</th>
			<th width="100px">Overall Level</th>
			<th width="100px">Crystals</th>
			<th width="100px">Vespene</th>
		</tr>
		<?php foreach ($this->paginator as $player): ?>
			<tr>
				<td><a href="<?= $this->url('player', ['action' => 'show', 'id' => $player->getId()]) ?>">
					<?= $this->escapeHtml($player->getId()) ?></a></td>
				<td><a href="<?= $this->url('player', ['action' => 'show', 'id' => $player->getId()]) ?>">
					<?= $this->escapeHtml($player->getName()) ?></a></td>
				<td><a href="<?= $this->url('player', ['action' => 'show', 'id' => $player->getId()]) ?>">
					<?= $this->escapeHtml($player->getSteamId()) ?></a></td>
				<td><?= $this->escapeHtml($player->getOverallLevel()) ?></td>
				<td><?= $this->escapeHtml($player->getCrystals()) ?></td>
				<td><?= $this->escapeHtml($player->getVespene()) ?></td>
			</tr>
		<?php endforeach; ?>
	</table>

	<?= $this->paginationControl(
		// The paginator object:
		$this->paginator,
		// The scrolling style:
		'sliding',
		// The partial to use to render the control:
		'partial/paginator',
		// The route to link to when a user clicks a control link:
		['route' => 'race']
	)?>
<?php else: ?>
	No player has been selected.
<?php endif; ?>

<!--?= $this->render('partials/html_footer.phtml'); ?-->
