<?php
/**
 * Player display page view
 * 
 * @version $Id: list.phtml,v 1.4 2007-12-04 16:54:49 seva Exp $
 */

#require_once 'Zend/Controller/Front.php';

// Render common HTML header
#echo $this->render('partials/html_header.phtml');
$title = 'Faction List:';
$this->headTitle($title);
?>
<h2><?= $this->escapeHtml($title) ?></h2>

<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escape($this->error); ?>
	</div>
<?php elseif (count($this->paginator)): ?>
	<div class="faction_container" width="100%">
		<table class="faction_detail">
			<?php foreach ($this->paginator as $faction): ?>
				<tr>
					<td width="100%"><table width="100%">
						<tr>
							<table width="100%">
								<tr>
									<td><a href="<?= $this->url('faction', ['action' => 'show', 'id' => $faction->getId()]) ?>"><img src="/sc/img/<?= $faction->getImage() ?>" width="250" /></a></td>
									<td width="100%" style="vertical-align:top">
										<table class="faction_title" width="100%">
											<tr>
												<th width='100%' style="text-align: center;"><a href="<?= $this->url('faction', ['action' => 'show', 'id' => $faction->getId()]) ?>"><?= $this->escapeHtml($faction->getLongName()) ?></a></th>
											</tr>
										</table>
										<table width="100%">
											<tr>
												<td><?= $this->escapeHtml($faction->getDescription()) ?></td>
											</tr>
										</table>
									</td>
								</tr>
							</table>
						</tr>
					</td></table>
				</tr>
				<tr>
					<td width="100%"><img src="/sc/img/spacer.gif" width="100%" height="1"/></td>
				</tr>
			<?php endforeach; ?>
		</table>
	</div>

	<!--?= $this->paginationControl($this->paginator, 'Sliding', 'pagination_control.phtml'); ?-->
	<?= $this->paginationControl(
		// The paginator object:
		$this->paginator,
		// The scrolling style:
		'sliding',
		// The partial to use to render the control:
		'partial/paginator',
		// The route to link to when a user clicks a control link:
		['route' => 'faction']
	);?>
	
<?php else: ?>
	No factions have been selected.
<?php endif; ?>

<!--?= $this->render('partials/html_footer.phtml'); ?-->
