<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('JigglysFunhouse SourceCraft')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . 'img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style1.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <div id="everything">
            <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
                <div id="header" class="container">
                    <div class="navbar-header">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <a class="navbar-brand" href="<?= $this->url('home') ?>">
                            <img src="<?= $this->basePath('img/Jigglylogo.png') ?>" alt="Jiggly's FunHouse">
                        </a>
                    </div>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- ul class="navbar-nav">
                            <li class="nav-item active">
                                <a class="nav-link" href="<?= $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
                            </li>
                        </ul -->
                        <?= $this->navigation('navigation')
                                ->menu()
                                ->setMinDepth(0)
                                ->setMaxDepth(0)
                                ->setUlClass('nav navbar-nav')
                        ?>
                    </div>
                </div> <!-- #header -->
            </nav>
            <div id = "middle" class="container">
                <?= $this->navigation('navigation')
                    ->breadcrumbs()
                    ->setMinDepth(0)
                    ->setPartial('partial/breadcrumb')
                ?>
                <?= $this->content ?>
            </div> <!-- #middle -->
            <hr>
            <?php if (!isset($this->disableFooter) || !$this->disableFooter): ?>
                <footer id="footer" class="d-flex justify-content-center text-center copyright">
                    <div>
                        <span>&copy; 2021 Jigglys FunHouse, all rights reserved.</span><br>
                        <span>Team Fortress&reg; and the Team Fortress logo are trademarks and/or registered trademarks of Valve Corporation&reg;.</span><br>
                        <span>StarCraft&reg; II and Blizzard Entertainment&reg; are all trademarks or registered trademarks of Blizzard Entertainment in the United States and/or other countries.</span><br>
                        <span>This site is in no way associated with or endorsed by Blizzard Entertainment&reg; nor Valve Corporation&reg;.</span>
                    </div>
                </footer>
            <?php endif; ?>
        </div> <!-- #everything -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
